[project]
name = "embodied-gaussians"
requires-python = ">=3.11,<3.12"
authors = [{ name = "Jad Abou-Chakra" }]
description = "Physically Embodied Gaussian Splatting"
version = "0.1.0"
dependencies = [
    "warp-lang==1.7.1",
    "torch>=2.5.1,<3",
    "tyro",
    "torchvision",
    "tqdm",
    "zarr>=3.0.4,<3.1",
    "trio",
    "trio-util",
    "opencv-python",
    "glfw>=2.8.0,<3",
    "open3d>=0.18.0,<0.19.0",
    "marsoom @ git+https://github.com/jc211/marsoom.git@febe61df91a75df10063bfb420e9e68a9a8cd6a9",
    "torchcodec==0.3.0",
    "realsense @ git+https://github.com/davelearn/realsense.git@b3cc6bae06bfac0f8719ac95a7511815dac1213d",
    "isegm @ git+https://github.com/jc211/ritm_interactive_segmentation",
    "pydantic",
    # This is the newest Drake wheel compatible with the declared glibc 2.31 baseline.
    "drake @ https://github.com/RobotLocomotion/drake/releases/download/v1.26.0/drake-1.26.0-cp311-cp311-manylinux_2_31_x86_64.whl",
    "pyrealsense2>=2.54.2,<3",
]

[dependency-groups]
build = ["scikit-build-core>=0.10", "pybind11>=2.10"]
test = ["pytest>=8.3.5,<9"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = [{ platform = "linux-64", cuda = "12.8", glibc = "2.31" }]

[tool.pixi.pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu128"]

[tool.pixi.dependencies]
ffmpeg = "*"
cuda = "12.8.*"
cuda-version = "<=12.8"
cmake = "*"
ninja = "*"
pip = ">=25.0.1,<26"

[tool.pixi.pypi-dependencies]
embodied-gaussians = { path = ".", editable = true }

[tool.pixi.environments]
default = { features = ["build", "test"], solve-group = "default" }

[tool.pixi.tasks]
build-gsplat = { cmd = "pip install git+https://github.com/nerfstudio-project/gsplat.git@d23d7ca5dd26c3756967304b621ae88521672ed5 --no-build-isolation", env = { TORCH_CUDA_ARCH_LIST = "native" } }
build-pysegreduce = { cmd = "pip install git+https://github.com/jc211/pysegreduce.git@67fde3df40c6220ed5a0ad38eac2caabf019e0c9 --no-build-isolation", env = { CUDAARCHS = "native" } }
build = { depends-on = ["build-gsplat", "build-pysegreduce"] }
test = "pytest"
demo = "python examples/example_embodied_pusht_offline.py"

[tool.pixi.activation]
env = { LD_LIBRARY_PATH = "$CONDA_PREFIX/lib:$LD_LIBRARY_PATH" }
