[project]
name = "embodied-gaussians"
requires-python = ">=3.11,<3.12"
authors = [{name="Jad Abou-Chakra"}]
description = "Physically Embodied Guassian Splatting"
version = "0.1.0"
dependencies=[
    "warp-lang==1.7.1",
    "torch>=2.5.1,<3",
    "tyro",
    "torchvision",
    "tqdm", 
    "zarr>=3.0.4,<3.1",
    "trio",
    "trio-util",
    "opencv-python",
    "glfw>=2.8.0,<3",
    "pytest",
    "open3d>=0.18.0,<0.19.0",
    "marsoom @ git+https://github.com/jc211/marsoom.git@febe61df91a75df10063bfb420e9e68a9a8cd6a9",

    "torchcodec==0.1.1",
    "realsense @ git+https://github.com/davelearn/realsense.git@b3cc6bae06bfac0f8719ac95a7511815dac1213d",

    "isegm @ git+https://github.com/jc211/ritm_interactive_segmentation", 

    # "sam-2 @ git+https://github.com/facebookresearch/sam2.git",

    "pydantic", # TODO: Remove in favor of dataclasses only
    "drake@https://github.com/RobotLocomotion/drake/releases/download/v1.26.0/drake-1.26.0-cp311-cp311-manylinux_2_31_x86_64.whl",  # Remove drake entirely when we create our own zero-order-hold
    "pyright",
    "pyrealsense2>=2.54.2,<3",
    "ruff>=0.11.11,<0.12"
    ]


[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-options]
no-build-isolation = ["gsplat", "pysegreduce"]
extra-index-urls = ["https://download.pytorch.org/whl/cu124"]

[tool.pixi.system-requirements]
cuda = "12.4"

[tool.pixi.dependencies]
ffmpeg = "*"
cuda = "12.4.*"
cuda-version = "<=12.4"
pip = ">=25.0.1,<26"


[tool.pixi.pypi-dependencies]
embodied_gaussians = { path = ".", editable = true }
pysegreduce = { path = "dependencies/segreduce", editable = true }


[tool.pixi.tasks]
build_gsplat = "pip install git+https://github.com/nerfstudio-project/gsplat.git"
build = {depends-on=["build_gsplat"]}
demo = "python examples/example_embodied_pusht_offline.py"
format = "ruff format"
lint = "ruff check"
typecheck = "pyright"
check = [{ task = "format" }, { task = "lint" }, { task = "typecheck" }]

[tool.pixi.activation]
env = {LD_LIBRARY_PATH = "$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"}

[tool.ruff]
include = ["pyproject.toml", "src/**/*.py", "scripts/**/*.py"]
line-length = 150

[tool.ruff.lint]
select = ["E", "F"]

[tool.pyright]
include = [
    "src"
]