[project]
name = "embodied-gaussians"
requires-python = ">=3.11,<3.12"
authors = [{name="Jad Abou-Chakra"}]
description = "Physically Embodied Guassian Splatting"
version = "0.1.0"
dependencies=[
    "warp-lang==1.7.0",
    "torch>=2.5.1,<3",
    "tyro",
    "torchvision",
    "tqdm", 
    "zarr>=3.0.4,<3.1",
    "trio",
    "trio-util",
    "opencv-python",
    "pytest",
    "marsoom @ git+https://github.com/jc211/marsoom.git",

    "realsense @ git+https://github.com/jc211/realsense.git",

    "isegm @ git+https://github.com/jc211/ritm_interactive_segmentation", 

    # "sam-2 @ git+https://github.com/facebookresearch/sam2.git",

    "pydantic", # TODO: Remove in favor of dataclasses only
    "drake@https://github.com/RobotLocomotion/drake/releases/download/v1.37.0/drake-1.37.0-cp311-cp311-manylinux_2_35_x86_64.whl", # Remove drake entirely when we create our own zero-order-hold
]


[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-options]
no-build-isolation = ["gsplat", "pysegreduce"]

[tool.pixi.system-requirements]
cuda = "12.4"

[tool.pixi.dependencies]
ffmpeg = "*"
open3d = "*"
cuda = "12.4.*"
cuda-version = "<=12.4"
glfw = "*"
pip = ">=25.0.1,<26"
pyrealsense2 = ">=2.54.2,<3"

[tool.pixi.pypi-dependencies]
embodied_gaussians = { path = ".", editable = true }
torchcodec = { version = "==0.1.1", index = "https://download.pytorch.org/whl/cu124"}


[tool.pixi.tasks]
build_gsplat = "pip install git+https://github.com/nerfstudio-project/gsplat.git@d23d7ca5dd26c3756967304b621ae88521672ed5 --no-build-isolation"
build_pysegreduce = "pip install ./dependencies/segreduce --no-build-isolation"
build = {depends-on=["build_gsplat", "build_pysegreduce"]}
demo = "python examples/example_embodied_pusht_offline.py"

[tool.pixi.activation]
env = {LD_LIBRARY_PATH = "$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"}
